sudo: true

language: node_js

node_js:
  - 6

services:
  - mysql
  - postgresql

env:
  global:
    - CXX=g++-4.8
    - NODE_ENV=test

  matrix:
    - DATABASE_DRIVER: sqlite3

    - DATABASE_DRIVER: mysql2
      DATABASE_URL: mysql://travis@127.0.0.1:3306/lux_test

    - DATABASE_DRIVER: pg
      DATABASE_URL: postgresql://postgres@127.0.0.1:5432/lux_test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-4.8
      - gcc-4.8
      - postgresql-9.4

cache:
  directories:
  - node_modules
  - test/test-app/node_modules

before_script:
  - bash -e scripts/travis/before-script.sh

install:
  - bash -e scripts/travis/install.sh

notifications:
  email: false
