sudo: true

language: node_js

node_js:
  - "6"
  - "5"

services:
  - mysql

before_script:
  - cat test/fixtures/data.sql | mysql -u travis
  - npm install -g gulp
  - npm link

env:
  global:
    - CXX=g++-4.8
    - NODE_ENV=test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-4.8
