build: off
platform: x64

services:
  - mysql
  - postgresql

environment:
  nodejs_version: 6
  NODE_ENV: test

  matrix:
    - DATABASE_DRIVER: sqlite3
    - DATABASE_DRIVER: mysql2
      DATABASE_USERNAME: root

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
  - npm link
  - ps: Set-Location C:\projects\lux\test\test-app
  - npm install
  - ps: Set-Location C:\projects\lux

test_script:
  - npm run flow
  - npm run lint
  - npm test
