build: off
platform: x64
services:
  - mysql
  - postgresql
environment:
  MYSQL: C:\Program Files\MySql\MySQL Server 5.7\bin\mysql
  NODE_ENV: test
  MYSQL_PWD: Password12!
  CREATE_DATABASE: CREATE DATABASE lux_test;
  DROP_DATABASE: DROP DATABASE IF EXISTS lux_test;
  matrix:
    - DATABASE_DRIVER: sqlite3
    - DATABASE_DRIVER: mysql2
      DATABASE_USERNAME: root
install:
  - ps: Install-Product node 6 $env:platform
  - npm install
  - npm link
  - ps: Set-Location C:\projects\lux\test\test-app
  - npm install
  - ps: Set-Location C:\projects\lux
before_test:
  - ps: Invoke-Expression "& '$mysql' -e '$DROP_DATABASE' -u root"
  - ps: Invoke-Expression "& '$mysql' -e '$CREATE_DATABASE' -u root"
  - ps: Remove-Item C:\projects\lux\test\test-app\db\* -Force -Include *.sqlite
  - ps: Write-Host $null >> C:\projects\lux\test\test-app\db\lux_test_test.sqlite
test_script:
  - npm run flow
  - npm run lint
  - npm test
