// flow-typed signature: f0c658ea7c670a61e0162dc62aa25d20
// flow-typed version: <<STUB>>/remark-cli_v3.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remark-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remark-cli/cli.js' {
  declare module.exports: $Exports<'remark-cli/cli'>;
}
